In [ ]:
#1
import numpy as np

In [ ]:
#2
print(np.__version__)
np.show_config()


In [ ]:
#3
z = np.arange(10)
z

In [ ]:
#4
z = np.arange(10)
#z.size
#z.itemsize
z.itemset

In [ ]:
#5
np.info(np.add)


In [ ]:
#6
x = np.arange(10)
x[4] = 1
x

In [ ]:
#7
x = np.arange(10,50)
x = np.reshape(x,(40,1))
x.shape


In [ ]:
#8
x = np.arange(50)
x
x = x[::-1]
x

In [ ]:
#9
x = np.arange(9)
x = np.reshape(x,(3,3))
x
x.shape

In [ ]:
#10
x = np.nonzero([1,2,0,0,6,7])
x



In [ ]:
#11
x = np.eye(3,3)
x



In [ ]:
#12
x = np.random.random((3,3,3))
x

x.shape

In [ ]:
#13
x = np.random.random((10,10))
print(x.min(),x.max())
x

In [ ]:
#14
x = np.random.random(30)
m = x.mean()
m
x.ndim

In [ ]:
#15
x = np.ones((10,10))

x
x[1:-1,1:-1] = 0
x

In [ ]:
#16
x = np.ones((10,10))
x = np.pad(x,pad_width=1,mode="constant",constant_values = 0)
x


In [ ]:
#17
#18
x = np.diag(1+np.arange(4),k = -1)
x



In [ ]:
#19
x = np.zeros((8,8),dtype=int)
x[1::2,1::2] = 1
x[::2,::2] = 1
x


In [ ]:
#20
np.unravel_index(100,(6,7,8))



In [ ]:
#21
x = np.tile(np.array([[0,1],[1,0]]),(4,4))

x.shape


In [ ]:
#22
#z = np.arange(25).reshape(5,5)

x = np.random.random((5,5))

zmax,zmin = x.max(),x.min()

x = (x-zmin) / (zmax-zmin)
x

In [ ]:
#23
#24
x = np.dot(np.ones((5,3)),np.ones((3,2)))
x


In [ ]:
#z = np.arange(11)
z = np.random.random((4,4))*10
z[(3<z)&(z<=8)] *=-1
z


In [ ]:
print(np.sum(range(5),-1))




In [ ]:
#30
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
x =np.intersect1d(z1,z2)
x


In [ ]:

import numpy as np
x = np.random.random(10)
x
x = np.random.uniform(0,10,10)
x

In [ ]:
print(np.floor(x))
print(x.astype(int))


In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
x

In [ ]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)

#x = generate()
x


In [ ]:
def generate():
    for i in range(10):
        print(i)

x = generate()
x

In [ ]:
#39
x = np.linspace(0,1,11,endpoint=False)[1:]
x



In [ ]:
x = np.arange(10)
x = np.random.random(10)
x

In [ ]:
#40
x = np.linspace(0,10,13)
z = np.random.random(10)
z.sort()
z

In [ ]:
#41
z = np.arange(10)
z
x = np.add.reduce(z)
x

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal

In [ ]:
equal = np.array_equal(A,B)
equal
x = 2
r = np.sqrt(x)
r

In [ ]:
#44
x = np.random.random((10,2))
X,Y = x[:,0],x[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
T
print(X)


In [ ]:
x = np.arange(10)
x[x.argmax()] = 1
x.argmax()

In [ ]:
np.set_printoptions(threshold=np.nan)
x = np.zeros((10,10))
x


In [ ]:
x = np.arange(100)
v =np.random.uniform(0,100)
index = (np.abs(x-v)).argmin()
print(x[index])
print(v)

In [ ]:
x = np.array([2,3,1,4,5,6])
v = x.argmin()
x[v]


In [ ]:
x = np.arange(10,dtype = np.int32)
x = x.astype(np.float32,copy=False)
x

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)
for index,value in np.ndenumerate(x):
    print(index,value)


In [ ]:
X, y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
x.ndim

In [ ]:
D = np.sqrt(X*X+Y*Y)
sigma,mu = 1.0,0.0
G = np.exp(-(D-mu)**2 / )

In [ ]:
import numpy as np
import pandas as pd



In [ ]:
data = np.array([1,2,3])
data


In [ ]:
data.shape

In [ ]:
data = np.reshape(data,(1,3))
data.shape


In [ ]:
data

In [ ]:
import numpy as np
x = np.random.randint(0,2,(6,3))
z = np.ascontiguousarray(x).view(np.dtype((np.void,x.dtype.itemsize * x.shape[1])))
_,idx=np.unique(z,return_index=True)
x[idx]


In [ ]:
x = np.array([0,1,2,3,15,16,32,64,128])
b = ((x.reshape(-1,1)&))


In [ ]:
x = np.arange(10000)
np.random.shuffle(x)
x[np.argsort(x)[-5:]]

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)



In [ ]:
x = np.ones((16,16))
k = 4
s = np.add.reduceat((np.add.reduceat()))

In [ ]:
x = np.random.randint(0,20,50)
print(x.argmax())
print(x[x.argmax()])
#np.bincount(x).argmax()

In [ ]:
x  =np.arange(36).reshape((6,6))
x

In [ ]:
x[[0,1]] = x[[1,0]]
x


In [ ]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
z = x*y[:,:,None]
#y[:,:,None].shape

In [ ]:
x = np.array([1,2,3,4,5])
n = 3
x0 = np.zeros(len(x)+(len(x)-1)*n)
x0[::n+1] = x
x0



In [ ]:
import numpy as np




In [ ]:
a = np.arange(12)*2
a
i = np.array([1,1,3,8,5])
a[i]


In [ ]:
j = np.array([[3,4],[9,7]])
x = a[j]
x.ndim

In [ ]:
x = np.arange(30)
x.shape = (2,-1,3)
x.shape

In [ ]:
import numpy as np

x = np.arange(0,10,2)
x
y = np.arange(5)
y




In [ ]:
import numpy as np
m = np.vstack([x,y])
m


In [ ]:
m[[1,0],:]=m[[0,1],:]
m



In [ ]:


import pandas as pd
import numpy as np




In [6]:
import numpy as np
x = np.array([1,2,3])
x




array([1, 2, 3])

In [9]:
y = np.random.randint(3,5,4)
y = np.random.random(6)
y


array([0.32063099, 0.20668082, 0.73460339, 0.65595425, 0.79958793,
       0.4333065 ])

In [10]:
x = np.array([2,3,4,5])
x



array([2, 3, 4, 5])

In [ ]:
import torch





In [11]:
x = torch.tensor([1,2,3])


NameError: name 'torch' is not defined

In [15]:
import torch 


ModuleNotFoundError: No module named 'torch'