In [1]:
import torch




ModuleNotFoundError: No module named 'torch'

In [4]:
x = torch.tensor([1,2,3])
type(x)

torch.Tensor

In [5]:
x = torch.empty(5,3)
x




tensor([[1.0469e-38, 4.2246e-39, 9.6429e-39],
        [1.0653e-38, 8.9082e-39, 9.2755e-39],
        [1.0837e-38, 8.4490e-39, 1.1112e-38],
        [4.1328e-39, 1.0653e-38, 9.0000e-39],
        [8.4490e-39, 8.7245e-39, 1.0102e-38]])

In [6]:
x = torch.rand(5,3)
x



tensor([[0.5124, 0.6114, 0.3401],
        [0.6785, 0.1866, 0.2456],
        [0.2717, 0.4255, 0.4598],
        [0.1060, 0.6790, 0.7904],
        [0.2871, 0.6442, 0.2453]])

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x



tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = torch.tensor([5.5,3.0])
x

tensor([5.5000, 3.0000])

In [9]:
x = torch.ones(5,3,dtype=torch.double)
x



tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
x = torch.rand_like(x,dtype=torch.float)
x

tensor([[0.6976, 0.1677, 0.2276],
        [0.0747, 0.8216, 0.4964],
        [0.5534, 0.9023, 0.6418],
        [0.3250, 0.8586, 0.6135],
        [0.1360, 0.5892, 0.6608]])

In [16]:
x = torch.randn(5,3)

x.size()


torch.Size([5, 3])

In [15]:
import numpy as np
x = np.random.random((5,3))



AttributeError: module 'numpy' has no attribute 'ramdom'

In [18]:
x = torch.randn(5,3)
y = torch.randn(5,3)
x + y


tensor([[-1.1223,  2.3536,  0.7538],
        [-2.4890,  0.8818, -1.2060],
        [-1.4840, -0.0254, -0.5401],
        [-1.3282,  0.3763, -0.1575],
        [ 0.0056, -0.4441,  0.3780]])

In [19]:
print(x[:,1])




tensor([ 1.8040,  0.0617,  0.7371,  1.0717, -0.6005])


In [28]:
x = torch.randn(4,4)
x = x.reshape(16)
x.shape
y = np.random.random((4,4))
y = y.reshape((16,1))
y.shape

(16, 1)

In [30]:
x = torch.randn(2,8)
x = x.reshape(-1,4)
x


torch.Size([4, 4])

In [45]:
x = torch.randn(4)
x


tensor([ 0.8279, -0.5915,  0.4517, -0.9657])

TypeError: item() takes no arguments (1 given)

In [53]:
a = torch.ones((4,4))
b = a.numpy()
b


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [57]:
a.add_(1)
a
b

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]], dtype=float32)

In [58]:
a = np.ones((5,5))
b = torch.from_numpy(a)
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [60]:
c = torch.tensor(a)
c
b.allclose(c)

True

In [64]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [66]:
y = x+2
y.grad_fn


In [68]:
z = y*y*3
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [69]:
out.backward()

In [70]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [79]:
x = torch.randn(3,requires_grad=True)
x

tensor([-0.2617, -1.3065,  1.5429], requires_grad=True)

In [80]:
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)


tensor([-133.9815, -668.9503,  789.9557], grad_fn=<MulBackward0>)


In [84]:
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad())

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [85]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)



RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [2]:
import torch


x = torch.tensor([1,2,3])
x



tensor([1, 2, 3])

In [4]:
y = torch.tensor([2,3,4])
z = x * y
z






tensor([ 2,  6, 12])

In [7]:
y = torch.tensor([1,23,3])
c = torch.tensor([3,4,5])
x = torch.tensor([2,34,2])
p = torch.tensor([2,3,4])
x = torch.randn(4)
x

x - torch.random(2,3,2)
x


TypeError: 'module' object is not callable

In [8]:
y = torch.randn(5)
y



tensor([-0.2000,  0.2055, -0.5426, -0.6227, -1.4080])

In [9]:
x = torch.randn(9)
x



tensor([-0.0218,  0.4089,  0.4909,  1.7588,  0.3674, -1.4724, -0.5364,  1.4041,
        -1.0525])

In [10]:

import numpy as np
import pandas as pd

In [11]:
x = np.array([1,2,3,4])
x



array([1, 2, 3, 4])